[versions]
proto = "3.19.0"
grpc = "1.41.0"

[libraries]
javax-annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.2" }

protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "proto" }

grpc-netty = { module = "io.grpc:grpc-netty", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
